# This is a basic workflow to Relay Weather info from SenseCAP LoRaWAN S2120 Weather Station to Windy Stations

name: WAU-Wait-And-Update 1

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #schedule: # every 10 min
  #- cron: "*/10 * * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  # This workflow contains a single job called "WAU"
  wau-wait-and-update:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: wau-wait-and-update
        run: |
          date "+%H:%M:%S %d/%m/%y"
          sudo apt -y install mosquitto-clients nodejs
          date "+%H:%M:%S %d/%m/%y"
          ./script-pws.sh ${{ secrets.SENSECAP_URL }} ${{ secrets.OID }} ${{ secrets.APIAccessKey }} ${{ secrets.EUI }} ${{ secrets.WINDY_API_KEY }}

